import {
  PlaylistIcon,
  CollectionIcon,
  StudyPackIcon,
  EnvelopeIcon,
  VaultIcon,
} from '../components/saved/icons/ContainerIcons';

export const CONTAINER_TYPE_CONFIG = {
  envelope: {
    type: 'envelope',
    label: 'Learning Envelope',
    plural: 'Envelopes',
    displayTitle: 'Learning Envelope',
    badgeLabel: 'LEARNING ENVELOPE',
    headerTitle: 'Save to envelope...',
    btnLabel: 'New envelope',
    typeTitle: 'Courses & Learning Tracks',
    allowedItemTypes: ['course', 'track', 'syllabus'],
    emptyTitle: 'No envelopes yet',
    emptySubtitle: 'Create an envelope to bundle courses and tracks.',
    emptyDesc: 'Save courses, syllabi, and learning tracks to this envelope.',
    ctaLabel: 'Browse Courses',
    exploreUrl: '/notes',
    icon: EnvelopeIcon,
    accent: '#7C3AED',
    avatarGradient: 'linear-gradient(135deg, #7C3AED 0%, #A855F7 100%)',
    ctaGradient: 'linear-gradient(135deg, #7C3AED 0%, #9333EA 100%)',
  },
  packs: {
    type: 'packs',
    label: 'Study Pack',
    plural: 'Study Packs',
    displayTitle: 'Study Pack',
    badgeLabel: 'STUDY PACK',
    headerTitle: 'Save to study pack...',
    btnLabel: 'New study pack',
    typeTitle: 'Study Notes & Documents',
    allowedItemTypes: ['note', 'notes', 'question_paper', 'pdf'],
    emptyTitle: 'No study packs yet',
    emptySubtitle: 'Create a study pack to group semester notes and PYQs.',
    emptyDesc: 'Save study notes, question papers, and PDFs to this study pack.',
    ctaLabel: 'Browse Notes & PYQs',
    exploreUrl: '/notes',
    icon: StudyPackIcon,
    accent: '#10B981',
    avatarGradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    ctaGradient: 'linear-gradient(135deg, #10B981 0%, #3B82F6 100%)',
  },
  study_pack: {
    type: 'packs',
    label: 'Study Pack',
    plural: 'Study Packs',
    displayTitle: 'Study Pack',
    badgeLabel: 'STUDY PACK',
    headerTitle: 'Save to study pack...',
    btnLabel: 'New study pack',
    typeTitle: 'Study Notes & Documents',
    allowedItemTypes: ['note', 'notes', 'question_paper', 'pdf'],
    emptyTitle: 'No study packs yet',
    emptySubtitle: 'Create a study pack to group semester notes and PYQs.',
    emptyDesc: 'Save study notes, question papers, and PDFs to this study pack.',
    ctaLabel: 'Browse Notes & PYQs',
    exploreUrl: '/notes',
    icon: StudyPackIcon,
    accent: '#10B981',
    avatarGradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    ctaGradient: 'linear-gradient(135deg, #10B981 0%, #3B82F6 100%)',
  },
  collection: {
    type: 'collection',
    label: 'Collection',
    plural: 'Collections',
    displayTitle: 'Collection',
    badgeLabel: 'COLLECTION',
    headerTitle: 'Save to collection...',
    btnLabel: 'New collection',
    typeTitle: 'Saved Posts & Articles',
    allowedItemTypes: ['post', 'article', 'discussion'],
    emptyTitle: 'No collections yet',
    emptySubtitle: 'Create a collection to organize your saved posts and articles.',
    emptyDesc: 'Save community posts, threads, and articles to this collection.',
    ctaLabel: 'Explore Community Feed',
    exploreUrl: '/feed',
    icon: CollectionIcon,
    accent: '#9333EA',
    avatarGradient: 'linear-gradient(135deg, #9333EA 0%, #EC4899 100%)',
    ctaGradient: 'linear-gradient(135deg, #9333EA 0%, #FF5E62 100%)',
  },
  vaults: {
    type: 'vaults',
    label: 'Code Vault',
    plural: 'Code Vaults',
    displayTitle: 'Code Vault',
    badgeLabel: 'CODE VAULT',
    headerTitle: 'Save to code vault...',
    btnLabel: 'New code vault',
    typeTitle: 'Saved Code Snippets',
    allowedItemTypes: ['snippet', 'code_snippet', 'gist'],
    emptyTitle: 'No code vaults yet',
    emptySubtitle: 'Create a vault to store code snippets and algorithms.',
    emptyDesc: 'Save code blocks, gists, and algorithms to this code vault.',
    ctaLabel: 'Explore Code Snippets',
    exploreUrl: '/feed',
    icon: VaultIcon,
    accent: '#F59E0B',
    avatarGradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
    ctaGradient: 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)',
  },
  snippet_notebook: {
    type: 'vaults',
    label: 'Code Vault',
    plural: 'Code Vaults',
    displayTitle: 'Code Vault',
    badgeLabel: 'CODE VAULT',
    headerTitle: 'Save to code vault...',
    btnLabel: 'New code vault',
    typeTitle: 'Saved Code Snippets',
    allowedItemTypes: ['snippet', 'code_snippet', 'gist'],
    emptyTitle: 'No code vaults yet',
    emptySubtitle: 'Create a vault to store code snippets and algorithms.',
    emptyDesc: 'Save code blocks, gists, and algorithms to this code vault.',
    ctaLabel: 'Explore Code Snippets',
    exploreUrl: '/feed',
    icon: VaultIcon,
    accent: '#F59E0B',
    avatarGradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
    ctaGradient: 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)',
  },
  playlist: {
    type: 'playlist',
    label: 'Playlist',
    plural: 'Playlists',
    displayTitle: 'Video Playlist',
    badgeLabel: 'VIDEO PLAYLIST',
    headerTitle: 'Save to playlist...',
    btnLabel: 'New playlist',
    typeTitle: 'Saved Videos & Shorts',
    allowedItemTypes: ['video', 'short'],
    emptyTitle: 'No playlists yet',
    emptySubtitle: 'Create a playlist to organize your saved videos and shorts.',
    emptyDesc: 'Save long videos and dev shorts to this playlist.',
    ctaLabel: 'Explore Videos',
    exploreUrl: '/explore',
    icon: PlaylistIcon,
    accent: '#3B7CFF',
    avatarGradient: 'linear-gradient(135deg, #3B7CFF 0%, #6366F1 100%)',
    ctaGradient: 'linear-gradient(135deg, #3B7CFF 0%, #8B5CF6 100%)',
  },
};

export function getContainerConfig(type) {
  return CONTAINER_TYPE_CONFIG[type] || CONTAINER_TYPE_CONFIG.collection;
}
